# Site settings
author: Luke Chen
title: Learn.co blog
header-img: img/home-bg.png
email: luke.chen.2010@gmail.com
copyright_name: Luke Chen
description: > # this means to ignore newlines until "baseurl:"
  Blog for the Learn.co requirements
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  LukeChen2010

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
